#!/usr/bin/env python3
"""Ask a model to review the teaching content for things no tool can check.

Deliberately NOT asked: "does this code compile?" or "does this print what
it says?" -- verify_snippets and the labs-solutions repo answer those
exactly, and a model would only guess less reliably. This looks for the
pedagogical drift a compiler cannot see: a lecture and its lab disagreeing,
terminology shifting between decks, a hint that hands over the answer, a
practice question that needs something never taught.

Writes content-review-findings.md. Never edits the teaching material --
the workflow opens a pull request for a human to judge.

Auth: a single Amazon Bedrock API key in AWS_BEARER_TOKEN_BEDROCK. boto3
reads that environment variable itself -- the key cannot be passed as a
client argument -- so this script never handles the value.
Also: AWS_REGION, optional BEDROCK_MODEL_ID and REVIEW_SCOPE
(everything|lectures|labs|practice).
"""
import json
import os
import re
import sys
from pathlib import Path

MODEL = os.environ.get("BEDROCK_MODEL_ID",
                       "eu.anthropic.claude-sonnet-4-5-20250929-v1:0")
SCOPE = os.environ.get("REVIEW_SCOPE", "everything")
OUT = Path("content-review-findings.md")

BRIEF = """You are reviewing a university module's teaching material: a Java
course for first-year students. You are given one topic at a time: the lecture
deck and, where it exists, that topic's lab instructions.

Report ONLY things that would mislead or block a student. Specifically:

1. CONTRADICTIONS between the lecture and the lab (different definitions,
   different naming, a lab assuming something the lecture never taught).
2. TERMINOLOGY that drifts (the same idea called different things without
   saying they are the same).
3. HINTS that give away the whole answer instead of unblocking a step.
4. EXPLANATIONS that are wrong or out of date for modern Java (21+).
5. GAPS: an exercise needing a concept the material never introduces.

Do NOT report: style preferences, slide design, code that is deliberately
broken (marked no-compile or labelled as an error to predict), or anything
you are less than confident about. An empty report is a good outcome.

For each finding give: the file, a short quote locating it, what is wrong,
and the smallest fix. Be specific and brief. If you find nothing, say
"No findings." and stop."""


def read(p: Path, limit=90_000) -> str:
    t = p.read_text(encoding="utf-8")
    # strip the deck's CSS block: it is styling, not teaching content
    t = re.sub(r"<style>.*?</style>", "[styles omitted]", t, flags=re.DOTALL)
    return t[:limit]


def topics():
    for deck in sorted(Path("weeks").glob("*/slides.md")):
        topic = re.sub(r"^week-\d+-", "", deck.parent.name)
        lab = Path("labs/src/ie/atu") / topic.replace("-", "") / "README.md"
        parts = []
        if SCOPE in ("everything", "lectures"):
            parts.append(f"=== LECTURE ({deck}) ===\n{read(deck)}")
        if lab.is_file() and SCOPE in ("everything", "labs"):
            parts.append(f"=== LAB ({lab}) ===\n{read(lab)}")
        if parts:
            yield deck.parent.name, "\n\n".join(parts)


def main() -> None:
    try:
        import boto3
    except ImportError:
        sys.exit("boto3 not installed")
    if not os.environ.get("AWS_BEARER_TOKEN_BEDROCK"):
        sys.exit("AWS_BEARER_TOKEN_BEDROCK is not set - nothing to authenticate with")
    client = boto3.client("bedrock-runtime",
                          region_name=os.environ.get("AWS_REGION", "eu-west-1"))

    sections, errors, reviewed = [], [], 0
    for name, content in topics():
        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 2000,
            "system": BRIEF,
            "messages": [{"role": "user", "content": [{"type": "text", "text": content}]}],
        }
        try:
            resp = client.invoke_model(modelId=MODEL, body=json.dumps(body))
            text = json.loads(resp["body"].read())["content"][0]["text"].strip()
        except Exception as exc:                      # noqa: BLE001
            text = f"_Review failed for this topic: {exc}_"
        if text and "no findings" not in text.lower():
            sections.append(f"## {name}\n\n{text}\n")
        print(f"reviewed {name}: {'findings' if text and 'no findings' not in text.lower() else 'clean'}")

    header = (
        "# Content review findings\n\n"
        "_Generated by `.github/workflows/content-review.yml`. **Suggestions, "
        "not corrections** — every item needs a human decision before it is "
        "acted on. Compilation and output are already verified by CI; this "
        "looks only for pedagogical drift._\n\n"
    )
    OUT.write_text(header + ("\n".join(sections) if sections else
                             "No findings across the reviewed material.\n"),
                   encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(sections)} topic(s) with findings)")


if __name__ == "__main__":
    main()
